services:
  - type: web
    name: klh-canteen-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: QR_TOKEN_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: PORT
        value: 4000
