import "dotenv/config";
import { getPool } from "../src/lib/db.js";
import { query, sql } from "../src/db/sql.js";

/**
 * Removes orders generated by load testing so the kitchen board starts a demo
 * clean. Dry-run by default — pass --apply to actually delete.
 *
 * Only orders are touched. Users, menu items, and categories are never
 * affected. Reserved stock is handed back so cancelled test orders don't leave
 * portions permanently spoken for.
 */
const pool = getPool(process.env.DATABASE_URL!);
const apply = process.argv.includes("--apply");

async function counts() {
  const [{ rows: users }, { rows: orders }, { rows: items }] = await Promise.all([
    query<{ count: string }>(pool, sql`SELECT COUNT(*)::text AS count FROM "User"`),
    query<{ count: string }>(pool, sql`SELECT COUNT(*)::text AS count FROM "Order"`),
    query<{ count: string }>(pool, sql`SELECT COUNT(*)::text AS count FROM "MenuItem"`),
  ]);
  return {
    users: Number(users[0].count),
    orders: Number(orders[0].count),
    items: Number(items[0].count),
  };
}

const before = await counts();

const { rows: doomed } = await query<{ id: string; orderNumber: number; status: string; kitchen: string }>(
  pool,
  sql`SELECT "id", "orderNumber", "status", "kitchen" FROM "Order"`,
);

console.log(`Orders to remove: ${doomed.length}`);
console.log("Status breakdown:", doomed.reduce<Record<string, number>>((a, o) => {
  a[o.status] = (a[o.status] ?? 0) + 1;
  return a;
}, {}));
console.log("Untouched:", { users: before.users, menuItems: before.items });

if (!apply) {
  console.log("\nDRY RUN — nothing deleted. Re-run with --apply to execute.");
  await pool.end();
  process.exit(0);
}

const ids = doomed.map((o) => o.id);
if (ids.length > 0) {
  await query(pool, sql`DELETE FROM "OrderItem" WHERE "orderId" = ANY(${ids}::text[])`);
  await query(pool, sql`DELETE FROM "Order" WHERE "id" = ANY(${ids}::text[])`);
}
// Reservations died with their orders; rebuild the cached counter from zero.
await query(pool, sql`UPDATE "MenuItem" SET "reservedQty" = 0`);
await query(pool, sql`UPDATE "CollectionWindow" SET "bookedCount" = 0`);

console.log("\nAFTER:", await counts());
await pool.end();
