import "dotenv/config";
import { getPrisma } from "../src/lib/prisma.js";

/**
 * Removes orders generated by load testing so the kitchen board starts a demo
 * clean. Dry-run by default — pass --apply to actually delete.
 *
 * Only orders are touched. Users, menu items, and categories are never
 * affected. Reserved stock is handed back so cancelled test orders don't leave
 * portions permanently spoken for.
 */
const prisma = getPrisma(process.env.DATABASE_URL!);
const apply = process.argv.includes("--apply");

const before = {
  users: await prisma.user.count(),
  orders: await prisma.order.count(),
  items: await prisma.menuItem.count(),
};

const doomed = await prisma.order.findMany({
  select: { id: true, orderNumber: true, status: true, kitchen: true },
});

console.log(`Orders to remove: ${doomed.length}`);
console.log("Status breakdown:", doomed.reduce<Record<string, number>>((a, o) => {
  a[o.status] = (a[o.status] ?? 0) + 1;
  return a;
}, {}));
console.log("Untouched:", { users: before.users, menuItems: before.items });

if (!apply) {
  console.log("\nDRY RUN — nothing deleted. Re-run with --apply to execute.");
  await prisma.$disconnect();
  process.exit(0);
}

const ids = doomed.map((o) => o.id);
await prisma.orderItem.deleteMany({ where: { orderId: { in: ids } } });
await prisma.order.deleteMany({ where: { id: { in: ids } } });
// Reservations died with their orders; rebuild the cached counter from zero.
await prisma.menuItem.updateMany({ data: { reservedQty: 0 } });
await prisma.collectionWindow.updateMany({ data: { bookedCount: 0 } });

console.log("\nAFTER:", {
  users: await prisma.user.count(),
  orders: await prisma.order.count(),
  items: await prisma.menuItem.count(),
});
await prisma.$disconnect();
